account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import( 
    Home, 
    ArticleCreate, 
    GraphCreate,
    GraphList, 
    CategoryList, 
    CategoryCreate, 
    ArticleUpdate, 
    CategoryUpdate, 
    GraphUpdate, 
    ArticleDelete, 
    GraphDelete, 
    CategoryDelete,
    Profile,
    Registeration,
    activate,
)

app_name = 'account'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('article/create/', ArticleCreate.as_view(), name='article-create'),
    path('article/delete/<int:pk>/', ArticleDelete.as_view(), name="article-delete"),
    path('article/update/<int:pk>/', ArticleUpdate.as_view(), name="article-update" ),

	path('graph/list/', GraphList.as_view(), name='graphـlist'),
    path('graph/create/', GraphCreate.as_view(), name='graph-create'),
    path('graph/update/<int:pk>/', GraphUpdate.as_view(), name='graph-update'),
    path('graph/delete/<int:pk>/', GraphDelete.as_view(), name='graph-delete'),

    path('category/list/', CategoryList.as_view(), name='category-list'),
    path('category/create/', CategoryCreate.as_view(), name="category-create"),
    path('category/update/<int:pk>/', CategoryUpdate.as_view(), name="category-update" ),
    path('category/delete/<int:pk>/', CategoryDelete.as_view(), name='category-delete'),

    path('profile/', Profile.as_view(), name="profile")

]

blog/urls.py
from django.urls import path
from .views import ArticleList, ArticleDetail, Category, Author, ArticlePreview, Search

app_name = 'blog'
urlpatterns = [
	path('', ArticleList.as_view(), name='home'),
	path('page/<int:page>/', ArticleList.as_view(), name='home'),
	path('detail/<slug:slug>/', ArticleDetail.as_view(), name='detail'),
	path('preview/<int:pk>/', ArticlePreview.as_view(), name='preview'),
	path('category/<slug:slug>/', Category.as_view(), name='category'),
	path('category/<slug:slug>/page/<int:page>/', Category.as_view(), name='category'),
	path('author/<slug:username>/', Author.as_view(), name='author'),
	path('author/<slug:username>/page/<int:page>/', Author.as_view(), name='author'),
	path('search/', Search.as_view(), name='search'),
	path('search/page/<int:page>/', Search.as_view(), name='search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import Login, Registeration, activate

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),
    path("login/", Login.as_view(), name="login"),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('signup/', Registeration.as_view(), name="register"),  
    path('activate/<uidb64>/<token>/',activate, name='activate'),
    path('comment/', include('comment.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]



# from django.conf import settings
# from django.conf.urls.static import static

# urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.html import format_html
from django.urls import reverse 
from account.models import User
from comment.models.comments import Comment
from django.contrib.contenttypes.fields import GenericRelation

# my Managers
class CategoryManager(models.Manager):
	def Active(self):
		return self.filter(status=True)


class ArticleManager(models.Manager):
	def published(self):
		return self.filter(status='p')

# Create your models here.
class GetIpAddress(models.Model):
	ip_address = models.GenericIPAddressField(verbose_name="آی پی ادرس")

	def __str__(self):
		return str(self.ip_address)

	class Meta:
		verbose_name="ای پی"
		verbose_name_plural="ای پی ها"

class Graph(models.Model):
	title = models.CharField(max_length=200, verbose_name="عنوان گراف")

	graph_name_1 = models.CharField(max_length=200, verbose_name='نام گراف 1')
	graph_image_1 = models.ImageField(upload_to="images", verbose_name="عکس گراف 1")
	graph_number_1 = models.IntegerField(verbose_name="مقدار گراف 1")

	graph_name_2 = models.CharField(max_length=200, verbose_name='نام گراف 2')
	graph_image_2 = models.ImageField(upload_to="images", verbose_name="عکس گراف 2")
	graph_number_2 = models.IntegerField(verbose_name="مقدار گراف 2")

	graph_name_3 = models.CharField(max_length=200, verbose_name='نام گراف 3')
	graph_image_3 = models.ImageField(upload_to="images", verbose_name="عکس گراف 3")
	graph_number_3 = models.IntegerField(verbose_name="مقدار گراف 3")

	graph_name_4 = models.CharField(max_length=200, verbose_name='نام گراف 4')
	graph_image_4 = models.ImageField(upload_to="images", verbose_name="عکس گراف 4")
	graph_number_4 = models.IntegerField(verbose_name="مقدار گراف 4")

	graph_name_5 = models.CharField(max_length=200, verbose_name='نام گراف 5')
	graph_image_5 = models.ImageField(upload_to="images", verbose_name="عکس گراف 5")
	graph_number_5 = models.IntegerField(verbose_name="مقدار گراف 5")

	graph_name_6 = models.CharField(max_length=200, verbose_name='نام گراف 6')
	graph_image_6 = models.ImageField(upload_to="images", verbose_name="عکس گراف 6")
	graph_number_6 = models.IntegerField(verbose_name="مقدار گراف 6")

	graph_name_7 = models.CharField(max_length=200, verbose_name='نام گراف 7')
	graph_image_7 = models.ImageField(upload_to="images", verbose_name="عکس گراف 7")
	graph_number_7 = models.IntegerField(verbose_name="مقدار گراف 7")

	graph_name_8 = models.CharField(max_length=200, verbose_name='نام گراف 8')
	graph_image_8 = models.ImageField(upload_to="images", verbose_name="عکس گراف 8")
	graph_number_8 = models.IntegerField(verbose_name="مقدار گراف 8")

	graph_name_9 = models.CharField(max_length=200, verbose_name='نام گراف 9')
	graph_image_9 = models.ImageField(upload_to="images", verbose_name="عکس گراف 9")
	graph_number_9 = models.IntegerField(verbose_name="مقدار گراف 9")

	graph_name_10 = models.CharField(max_length=200, verbose_name='نام گراف 0')
	graph_image_10 = models.ImageField(upload_to="images", verbose_name="عکس گراف 0")
	graph_number_10 = models.IntegerField(verbose_name="مقدار گراف 0")

	def get_absolute_url(self):
		return reverse ('account:graphـlist')
 
	def __str__(self):
		return self.title

	class Meta():
		verbose_name='گراف'
		verbose_name_plural='گراف ها'


class ArticleCategory(models.Model):
	title = models.CharField(max_length=200, verbose_name="عنوان")
	slug = models.SlugField(unique=True, verbose_name="آدرس")
	position = models.IntegerField(verbose_name="پوزیشن")
	status = models.BooleanField(default=True, verbose_name="آیا نمایش داده شود؟")

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse ('account:category-list')

	class Meta:
		verbose_name="دسته بندی"
		verbose_name_plural="دسته بندی ها"

	objects = CategoryManager()


class Article(models.Model):
	STATUS_CHOICES = (
		('p', 'منتشر شده'),
		('d', 'پیش نویس'),
	)
	title = models.CharField(max_length=200, verbose_name="عنوان")
	user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name="article", verbose_name="نویسنده")
	slug = models.SlugField(unique=True, verbose_name="آدرس")
	comments = GenericRelation(Comment)
	Graph = models.ForeignKey(Graph, null=True, blank=True, on_delete=models.SET_NULL, related_name='graph', verbose_name="گراف")
	category = models.ManyToManyField(ArticleCategory, verbose_name="دسته بندی", related_name="article")
	description = models.TextField(verbose_name="توضیحات")
	thumbnail = models.ImageField(upload_to='images', verbose_name="عکس بندانگشتی")
	publish = models.DateTimeField(default=timezone.now, verbose_name="زمان انتشار")
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name="وضعیت")
	hits = models.ManyToManyField(GetIpAddress, through='articlehit', blank=True, verbose_name="بازدی ها")

	def __str__(self):
		return self.title

	def category_to_str(self):
		return ' ,'.join([ cate.title for cate in self.category.Active() ])
	category_to_str.short_description="دسته بندی ها"

	def show_thumbnail(self):
		return format_html('<img src="{}" width=200px; style="border-radius:5px;">'.format(self.thumbnail.url))
	show_thumbnail.short_description="عکس بندانگشتی"

	def get_absolute_url(self):
		return reverse ('account:home')

	class Meta():
		verbose_name="مقاله"
		verbose_name_plural="مقالات"
		ordering = ['-publish']


	objects = ArticleManager()


class ArticleHit (models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	ip_address = models.ForeignKey(GetIpAddress, on_delete=models.CASCADE)
	created = models.DateTimeField(auto_now_add=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
from .models import Article, ArticleCategory
from account.models import User
from account.mixins import UserAccessMixin
from django.db.models import Q

# Create your views here.
class ArticleList(ListView):
	queryset = Article.objects.published()
	paginate_by = 6


class ArticleDetail(DetailView):

	def get_object(self):
		slug = self.kwargs.get('slug')
		article = get_object_or_404(Article.objects.published(), slug=slug)
			
		ip_address = self.request.user.ip_address
		if ip_address not in article.hits.all():
			article.hits.add(ip_address)

		return article


class ArticlePreview(UserAccessMixin, DetailView):

	def get_object(self):
		pk = self.kwargs.get('pk')
		article = get_object_or_404(Article, pk=pk)
		return article


class Category(ListView):
	paginate_by = 6
	template_name = 'blog/category_list.html'

	def get_queryset(self):
		global category
		slug = self.kwargs.get('slug')
		category = get_object_or_404(ArticleCategory.objects.Active(), slug=slug)
		return category.article.published()

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['category'] =  category
		return context


class Author(ListView):
	paginate_by = 6
	template_name = 'blog/author_list.html'

	def get_queryset(self):
		global user
		username = self.kwargs.get('username')
		user = get_object_or_404(User, username=username)
		return user.article.published()

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['user'] =  user
		return context

class Search(ListView):
	paginate_by = 6
	template_name = 'blog/search_list.html'

	def get_queryset(self):
		global search
		search = self.request.GET.get('q')
		articles = Article.objects.filter(Q(description__icontains=search) | Q(title__icontains=search))
		return articles

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['search'] =  search
		return context

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load comment_tags %}
{% load ratings %}
{% load static %}
{% load humanize %}
{% block title %}{{object.title}}{% endblock %}
{% block main %}
	<!-- start the header section -->
	<header style="background:none; display: flex !important;">
		<div class="bg2" style="background-image: url({{object.thumbnail.url}});"></div>
		<h1 class="title" style="font-size: 45px;">{{object.title}}</h1>
		<div class="author-description" style="color: #fff;">نویسنده <a href="{%  url 'blog:author' object.user %}" style="color: #00b7ff; font-weight: bolder;">{{object.user.get_full_name}}</a> در <p class="time">{{object.publish|naturaltime}}</p></div>
		<div class="category" style="font-weight: bolder; margin: -30px auto 0px auto;">
			{% for cate in article.category.Active %}
				<a href="{% url 'blog:category' cate.slug %}" style="color: #fff;">#{{cate.title}}</a>
			{% endfor %}
		</div>
		<p style="margin-top: -15px;">{% ratings object %}</p>
		<div class="hits" style="color:#fff; margin-top: -15px;">
			بازدید ها : {{object.hits.count}}
		</div>
	</header>
	<!-- end the header section -->
	<!-- start the main section -->
	<div class="main-body">
		<div class="articles-wrapper">
		    {% if object.Graph  %}
			<div class="wrapper">
				<div class="line-wrapper">
					<div class="line" style="--per: {{object.Graph.graph_number_1}};">
						<p class="text">{{object.Graph.graph_number_1}}</p>
						<div class="img" style="background-image: url({{object.Graph.graph_image_1.url}});"></div>
					</div>
					<div class="line" style="--per: {{object.Graph.graph_number_2}};">
						<p class="text">{{object.Graph.graph_number_2}}</p>
						<div class="img" style="background-image: url({{object.Graph.graph_image_2.url}});"></div>
					</div>
					<div class="line" style="--per: {{object.Graph.graph_number_3}};">
						<p class="text">{{object.Graph.graph_number_3}}</p>
						<div class="img" style="background-image: url({{object.Graph.graph_image_3.url}});"></div>
					</div>
					<div class="line" style="--per: {{object.Graph.graph_number_4}};">
						<p class="text">{{object.Graph.graph_number_4}}</p>
						<div class="img" style="background-image: url({{object.Graph.graph_image_4.url}});"></div>
					</div>
					<div class="line" style="--per: {{object.Graph.graph_number_5}};">
						<p class="text">{{object.Graph.graph_number_5}}</p>
						<div class="img" style="background-image: url({{object.Graph.graph_image_5.url}});"></div>
					</div>
					<div class="line" style="--per: {{object.Graph.graph_number_6}};">
						<p class="text">{{object.Graph.graph_number_6}}</p>
						<div class="img" style="background-image: url({{object.Graph.graph_image_6.url}});"></div>
					</div>
					<div class="line" style="--per: {{object.Graph.graph_number_7}};">
						<p class="text">{{object.Graph.graph_number_7}}</p>
						<div class="img" style="background-image: url({{object.Graph.graph_image_7.url}});"></div>
					</div>
					<div class="line" style="--per: {{object.Graph.graph_number_8}};">
						<p class="text">{{object.Graph.graph_number_8}}</p>
						<div class="img" style="background-image: url({{object.Graph.graph_image_8.url}});"></div>
					</div>
					<div class="line" style="--per: {{object.Graph.graph_number_9}};">
						<p class="text">{{object.Graph.graph_number_9}}</p>
						<div class="img" style="background-image: url({{object.Graph.graph_image_9.url}});"></div>
					</div>
					<div class="line" style="--per: {{object.Graph.graph_number_10}};">
						<p class="text">{{object.Graph.title}}</p>
						<div class="img" style="background-image: url({{object.Graph.graph_image_10.url}});"></div>
					</div>
				</div>
				<div class="name-wrapper">
					<div class="name">
						<p>{{object.Graph.graph_name_1}}</p>
					</div>
					<div class="name">
						<p>{{object.Graph.graph_name_2}}</p>
					</div>
					<div class="name">
						<p>{{object.Graph.graph_name_3}}</p>
					</div>
					<div class="name">
						<p>{{object.Graph.graph_name_4}}</p>
					</div>
					<div class="name">
						<p>{{object.Graph.graph_name_5}}</p>
					</div>
					<div class="name">
						<p>{{object.Graph.graph_name_6}}</p>
					</div>
					<div class="name">
						<p>{{object.Graph.graph_name_7}}</p>
					</div>
					<div class="name">
						<p>{{object.Graph.graph_name_8}}</p>
					</div>
					<div class="name">
						<p>{{object.Graph.graph_name_9}}</p>
					</div>
					<div class="name">
						<p>{{object.Graph.graph_name_10}}</p>
					</div>
				</div>
			</div>
			{% endif %}
			<div class="article-wrapper" style="height: initial !important;">
				<div class="right">
					<p class="description" style="text-align: justify !important;">
						{{object.description|safe}}
					</p>
					<div class="comment">
						{% render_comments object request %}
						{% include_bootstrap %}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	<!-- end the main section -->
{% endblock %}

templates/blog/article_list.html
{% extends 'blog/list.html' %}


{% block page_title %}
	خانه
{% endblock %}
{% block page_title_2 %}
	<h1>آخرین مقالات</h1>
{% endblock %}
{% block previous_page %}
	{% url 'blog:home' page_obj.previous_page_number %}
{% endblock %}
{% block next_page %}
	{% url 'blog:home' page_obj.next_page_number %}
{% endblock %}

templates/blog/author_list.html
{% extends 'blog/list.html' %}


{% block page_title %}
	{{user.get_full_name}}
{% endblock %}
{% block page_title_2 %}
	<h1>نویسنده  : {{user.get_full_name}}</h1>
{% endblock %}
{% block previous_page %}
	{% url 'blog:author' user.username page_obj.previous_page_number %}
{% endblock %}
{% block next_page %}
	{% url 'blog:author' user.username page_obj.next_page_number %}
{% endblock %} 

templates/blog/base.html
{% load static %}
{% load ratings %}
{% load base_tags %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
    	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400" rel="stylesheet" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
		<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
		<link rel="stylesheet" href="{% static 'blog/assets/css/searchForm.css' %}">
		<link rel="stylesheet" href="{% static 'blog/assets/css/main.css' %}">

	<title>{% block title %}پیشگامان{% endblock %}</title>
</head>
{% autoescape on %}
    <body style="font-family: tanha !important;">
    	<!-- start the navigation -->
    	<nav>
    		{% category_navbar %}
    		<div class="right">
    			{% if not request.user.id == None %}
                    <a href="{% url 'account:profile' %}" target="_blank" class="profile">
                        <div class="img">
                        	<i class="fa fa-user" aria-hidden="true"></i>
                        </div>
                        <span>{{request.user.get_full_name}}</span>
                    </a>
                {% else %}
                    <a href="{% url 'login' %}">ورود </a>/
                    <a href="{% url 'register' %}">ثبت نام </a>
                {% endif %}
    		</div>
    	</nav>
    	<!-- end the navigation -->
    	{% block main %}{% endblock %}
    	<!--  start the footer section -->
    	<footer style="display:flex !important">
    		<ul style="display:flex !important">
    			<li class="facebook">
    				<a href="https://www.facebook.com/peshgamanfinance"><i class="fab fa-facebook"></i></a>
    			</li>
    			<li class="youtube">
    				<a href="https://youtube.com/c/Peshgaman"><i class="fab fa-youtube"></i></a>
    			</li>
    			<li class="telegram">
    				<a href="https://t.me/peshgaman_youtube"><i class="fab fa-telegram"></i></a>
    			</li>
    		</ul>
    	</footer>
    	<!--  end the footer section -->
    	<script src="{% static 'blog/assets/js/anime.min.js' %}"></script>
    	<script src="{% static 'blog/assets/js/main.js' %}"></script>
    	<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    </body>
{% endautoescape %}
</html>

templates/blog/category_list.html
{% extends 'blog/list.html' %}


{% block page_title %}
	{{category.title}}
{% endblock %}
{% block page_title_2 %}
	<h1>دسته بندی : {{category.title}}</h1>
{% endblock %}
{% block previous_page %}
	{% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}
{% block next_page %}
	{% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/blog/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load ratings %}
{% load base_tags %}
{% load humanize %}

{% block title %}{% block page_title %}
{% endblock %}{% endblock %}
{% block main %}

<!-- start the header section -->
	<header>
		<h1 class="title">پیشگامان</h1>
		<p class="text">اینجا جای اونایی است که به زمان ارزش میدهند!</p>
		<p class="text">به جمع ما خوش آمدید (:</p>
	</header>
<!-- end the header section -->
<!-- start the main section -->
	<div class="main-body">
		<div class="articles-wrapper">
			{% block page_title_2 %}{% endblock %}
			{% for article in object_list %}
				<div class="article-wrapper">
					<div class="left">
						<div class="img" style="background-image: url({{article.thumbnail.url}});"></div>
					</div>
					<div class="right">
						<a href="{% url 'blog:detail' article.slug %}">
							<h1 class="title">{{article.title}}{% ratings article %}</h1>
							<p class="description">
								{{article.description|safe|striptags|truncatewords:'30'}}
							</p>
						</a>
						<div class="author-description">نویسنده <a href="{% url 'blog:author' article.user.username %}">{{article.user.get_full_name}}</a> در <p class="time">{{article.publish|naturaltime}}</p></div>
						<div class="category">
							{% for cate in article.category.Active %}
								<a href="{% url 'blog:category' cate.slug %}">#{{cate.title}}</a>
							{% endfor %}
						</div>
						<div class="hits" style="color: #555; margin-right:5px;">
							بازدید ها :{{article.hits.count}}
						</div>
					</div>
				</div>
			{% empty %}
				<div>متاسفانه محتویاتی برای نمایش وجود ندارد</div>
			{% endfor %}
			{% if is_paginated %}
				<div class="pagination">
					{% if page_obj.has_previous %}
						<a href="{% block previous_page %}{% endblock %}">پوست های جدید</a>
					{% endif %}
					{% if page_obj.has_next %}
						<a href="{% block next_page %}{% endblock %}">پوست های قدیمی</a>
					{% endif %}
				</div>
			{% endif %}
		</div>
		{% last_month_view  request %}
	</div>
</div>
	<!-- end the main section -->
{% endblock %}

templates/blog/search_list.html
{% extends 'blog/list.html' %}


{% block page_title %}
	جستجو
{% endblock %}
{% block page_title_2 %}
	<h1>جستجو : {{search}}</h1>
{% endblock %}
{% block previous_page %}
	{% url 'blog:home'  page_obj.previous_page_number %}?q={{search}}
{% endblock %}
{% block next_page %}
	{% url 'blog:home' page_obj.next_page_number %}?q={{search}}
{% endblock %}