blog/urls.py
from django.urls import path
from .views import ArticleList, ArticleDetail, Category, Author, ArticlePreview, Search

app_name = 'blog'
urlpatterns = [
	path('', ArticleList.as_view(), name='home'),
	path('page/<int:page>/', ArticleList.as_view(), name='home'),
	path('detail/<slug:slug>/', ArticleDetail.as_view(), name='detail'),
	path('preview/<int:pk>/', ArticlePreview.as_view(), name='preview'),
	path('category/<slug:slug>/', Category.as_view(), name='category'),
	path('category/<slug:slug>/page/<int:page>/', Category.as_view(), name='category'),
	path('author/<slug:username>/', Author.as_view(), name='author'),
	path('author/<slug:username>/page/<int:page>/', Author.as_view(), name='author'),
	path('search/', Search.as_view(), name='search'),
	path('search/page/<int:page>/', Search.as_view(), name='search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import Login, Registeration, activate

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),
    path("login/", Login.as_view(), name="login"),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('signup/', Registeration.as_view(), name="register"),  
    path('activate/<uidb64>/<token>/',activate, name='activate'),
    path('comment/', include('comment.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]



# from django.conf import settings
# from django.conf.urls.static import static

# urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/parsials/category.html
<div class="left">
	<div class="btn"><i class="fa fa-bars"></i> آموزش</div>
	<ul>
		<li style="display:flex; align-items: center; justify-content: flex-end;">
			<div class="s128" style="min-height: 20px; height: 20px; background-color: transparent;">
		      <form action="{% url 'blog:search' %}">
		        <div class="inner-form">
		          <div class="row" style="width: 360px;">
		            <div class="input-field first" id="first" style="justify-content: flex-end;">
		              <input class="input input-specail" name='q' style="z-index: 20; font-family: tanha;" id="inputFocus" type="text" placeholder="جستجوی مقاله" />
		              <button type="submit"  class="clear">
		                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
		                  <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"></path>
		                </svg>
		              </button>
		            </div>
		          </div>
		        </div>
		      </form>
		    </div>
		</li>	
		<li>
			<a href="{% url 'blog:home' %}">خانه</a>
		</li>
		{% for cate in category %}
		<li>
			<a href="{% url 'blog:category' cate.slug %}">{{cate.title}}</a>
		</li>
		{% endfor %}
	</ul>
</div>

templates/parsials/last_month.html
{% load static %}
{% load ratings %}
{% load humanize %}
<div class="articles-wrapper" style="margin-top:50px;">
	<h1>مقالات داغ یک ماه اخیر</h1>
	{% for article in hot_Article %}
		<div class="article-wrapper">
			<div class="left">
				<div class="img" style="background-image: url({{article.thumbnail.url}});"></div>
			</div>
			<div class="right">
				<a href="{% url 'blog:detail' article.slug %}">
					<h1 class="title">{{article.title}}{% ratings article %}</h1>
					<p class="description">
						{{article.description|safe|striptags|truncatewords:'30'}}
					</p>
				</a>
				<div class="author-description">نویسنده <a href="{% url 'blog:author' article.user %}">{{article.user.get_full_name}}</a> در <p class="time">{{article.publish|naturaltime}}</p></div>
				<div class="category">
					{% for cate in article.category.Active %}
						<a href="{% url 'blog:category' cate.slug %}">#{{cate.title}}</a>
					{% endfor %}
				</div>
				<div class="hits" style="color: #555; margin-right:5px;">
					بازدید ها :{{article.hits.count}}
				</div>
			</div>
		</div>
	{% empty %}
			<div>متاسفانه محتویاتی برای نمایش وجود ندارد</div>
	{% endfor %}
</div>

<div class="articles-wrapper" style="margin-top:50px;">
	<h1>مقالات پربازدید یک ماه اخیر</h1>
	{% for article in last_month_view %}
		<div class="article-wrapper">
			<div class="left">
				<div class="img" style="background-image: url({{article.thumbnail.url}});"></div>
			</div>
			<div class="right">
				<a href="{% url 'blog:detail' article.slug %}">
					<h1 class="title">{{article.title}}{% ratings article %}</h1>
					<p class="description">
						{{article.description|safe|striptags|truncatewords:'30'}}
					</p>
				</a>
				<div class="author-description">نویسنده <a href="{% url 'blog:author' article.user %}">{{article.user.get_full_name}}</a> در <p class="time">{{article.publish|naturaltime}}</p></div>
				<div class="category">
					{% for cate in article.category.Active %}
						<a href="{% url 'blog:category' cate.slug %}">#{{cate.title}}</a>
					{% endfor %}
				</div>
				<div class="hits" style="color: #555; margin-right:5px;">
					بازدید ها :{{article.hits.count}}
				</div>
			</div>
		</div>
	{% empty %}
		<div>متاسفانه محتویاتی برای نمایش وجود ندارد</div>
	{% endfor %}
</div>